//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("eFast", "VendaVendaItens", "Venda", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TouchBalcao.Venda), "VendaItens", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TouchBalcao.VendaItens))]

// Original file name:
// Generation date: 21/12/2012 16:14:50
namespace TouchBalcao
{
    
    /// <summary>
    /// There are no comments for eFastContainer in the schema.
    /// </summary>
    public partial class eFastContainer : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new eFastContainer object using the connection string found in the 'eFastContainer' section of the application configuration file.
        /// </summary>
        public eFastContainer() : 
                base("name=eFastContainer", "eFastContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new eFastContainer object.
        /// </summary>
        public eFastContainer(string connectionString) : 
                base(connectionString, "eFastContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new eFastContainer object.
        /// </summary>
        public eFastContainer(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "eFastContainer")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for VendaItensSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<VendaItens> VendaItensSet
        {
            get
            {
                if ((this._VendaItensSet == null))
                {
                    this._VendaItensSet = base.CreateQuery<VendaItens>("[VendaItensSet]");
                }
                return this._VendaItensSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<VendaItens> _VendaItensSet;
        /// <summary>
        /// There are no comments for VendaSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Venda> VendaSet
        {
            get
            {
                if ((this._VendaSet == null))
                {
                    this._VendaSet = base.CreateQuery<Venda>("[VendaSet]");
                }
                return this._VendaSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Venda> _VendaSet;
        /// <summary>
        /// There are no comments for VendaItensSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToVendaItensSet(VendaItens vendaItens)
        {
            base.AddObject("VendaItensSet", vendaItens);
        }
        /// <summary>
        /// There are no comments for VendaSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToVendaSet(Venda venda)
        {
            base.AddObject("VendaSet", venda);
        }
    }
    /// <summary>
    /// There are no comments for eFast.VendaItens in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="eFast", Name="VendaItens")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class VendaItens : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new VendaItens object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="idVenda">Initial value of IdVenda.</param>
        /// <param name="cProd">Initial value of cProd.</param>
        /// <param name="xProd">Initial value of xProd.</param>
        /// <param name="qProd">Initial value of qProd.</param>
        /// <param name="vProd">Initial value of vProd.</param>
        /// <param name="vTotal">Initial value of vTotal.</param>
        /// <param name="vDesc">Initial value of vDesc.</param>
        /// <param name="vOutros">Initial value of vOutros.</param>
        /// <param name="custo">Initial value of Custo.</param>
        /// <param name="usuario">Initial value of Usuario.</param>
        /// <param name="garcom">Initial value of Garcom.</param>
        /// <param name="sProd">Initial value of sProd.</param>
        /// <param name="dhEmit">Initial value of dhEmit.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static VendaItens CreateVendaItens(int id, int idVenda, int cProd, string xProd, decimal qProd, decimal vProd, string vTotal, string vDesc, string vOutros, string custo, string usuario, string garcom, string sProd, string dhEmit)
        {
            VendaItens vendaItens = new VendaItens();
            vendaItens.Id = id;
            vendaItens.IdVenda = idVenda;
            vendaItens.cProd = cProd;
            vendaItens.xProd = xProd;
            vendaItens.qProd = qProd;
            vendaItens.vProd = vProd;
            vendaItens.vTotal = vTotal;
            vendaItens.vDesc = vDesc;
            vendaItens.vOutros = vOutros;
            vendaItens.Custo = custo;
            vendaItens.Usuario = usuario;
            vendaItens.Garcom = garcom;
            vendaItens.sProd = sProd;
            vendaItens.dhEmit = dhEmit;
            return vendaItens;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// Numero do Venda principal
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int IdVenda
        {
            get
            {
                return this._IdVenda;
            }
            set
            {
                this.OnIdVendaChanging(value);
                this.ReportPropertyChanging("IdVenda");
                this._IdVenda = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdVenda");
                this.OnIdVendaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _IdVenda;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdVendaChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdVendaChanged();
        /// <summary>
        /// Codigo Produto
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int cProd
        {
            get
            {
                return this._cProd;
            }
            set
            {
                this.OncProdChanging(value);
                this.ReportPropertyChanging("cProd");
                this._cProd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cProd");
                this.OncProdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _cProd;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProdChanged();
        /// <summary>
        /// Descrição do Produto
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string xProd
        {
            get
            {
                return this._xProd;
            }
            set
            {
                this.OnxProdChanging(value);
                this.ReportPropertyChanging("xProd");
                this._xProd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("xProd");
                this.OnxProdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _xProd;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnxProdChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnxProdChanged();
        /// <summary>
        /// Quantidade Produtos
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal qProd
        {
            get
            {
                return this._qProd;
            }
            set
            {
                this.OnqProdChanging(value);
                this.ReportPropertyChanging("qProd");
                this._qProd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("qProd");
                this.OnqProdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _qProd;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnqProdChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnqProdChanged();
        /// <summary>
        /// Valor Do Produto
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal vProd
        {
            get
            {
                return this._vProd;
            }
            set
            {
                this.OnvProdChanging(value);
                this.ReportPropertyChanging("vProd");
                this._vProd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("vProd");
                this.OnvProdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _vProd;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvProdChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvProdChanged();
        /// <summary>
        /// There are no comments for property vTotal in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string vTotal
        {
            get
            {
                return this._vTotal;
            }
            set
            {
                this.OnvTotalChanging(value);
                this.ReportPropertyChanging("vTotal");
                this._vTotal = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("vTotal");
                this.OnvTotalChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _vTotal;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvTotalChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvTotalChanged();
        /// <summary>
        /// There are no comments for property vDesc in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string vDesc
        {
            get
            {
                return this._vDesc;
            }
            set
            {
                this.OnvDescChanging(value);
                this.ReportPropertyChanging("vDesc");
                this._vDesc = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("vDesc");
                this.OnvDescChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _vDesc;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvDescChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvDescChanged();
        /// <summary>
        /// There are no comments for property vOutros in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string vOutros
        {
            get
            {
                return this._vOutros;
            }
            set
            {
                this.OnvOutrosChanging(value);
                this.ReportPropertyChanging("vOutros");
                this._vOutros = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("vOutros");
                this.OnvOutrosChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _vOutros;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvOutrosChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvOutrosChanged();
        /// <summary>
        /// There are no comments for property Custo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Custo
        {
            get
            {
                return this._Custo;
            }
            set
            {
                this.OnCustoChanging(value);
                this.ReportPropertyChanging("Custo");
                this._Custo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Custo");
                this.OnCustoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Custo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCustoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCustoChanged();
        /// <summary>
        /// There are no comments for property Usuario in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Usuario
        {
            get
            {
                return this._Usuario;
            }
            set
            {
                this.OnUsuarioChanging(value);
                this.ReportPropertyChanging("Usuario");
                this._Usuario = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Usuario");
                this.OnUsuarioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Usuario;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioChanged();
        /// <summary>
        /// There are no comments for property Garcom in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Garcom
        {
            get
            {
                return this._Garcom;
            }
            set
            {
                this.OnGarcomChanging(value);
                this.ReportPropertyChanging("Garcom");
                this._Garcom = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Garcom");
                this.OnGarcomChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Garcom;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGarcomChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGarcomChanged();
        /// <summary>
        /// Sequencia do Produto
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string sProd
        {
            get
            {
                return this._sProd;
            }
            set
            {
                this.OnsProdChanging(value);
                this.ReportPropertyChanging("sProd");
                this._sProd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("sProd");
                this.OnsProdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _sProd;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnsProdChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnsProdChanged();
        /// <summary>
        /// There are no comments for property dhEmit in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string dhEmit
        {
            get
            {
                return this._dhEmit;
            }
            set
            {
                this.OndhEmitChanging(value);
                this.ReportPropertyChanging("dhEmit");
                this._dhEmit = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("dhEmit");
                this.OndhEmitChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _dhEmit;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndhEmitChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndhEmitChanged();
        /// <summary>
        /// There are no comments for Venda in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eFast", "VendaVendaItens", "Venda")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Venda Venda
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Venda>("eFast.VendaVendaItens", "Venda").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Venda>("eFast.VendaVendaItens", "Venda").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Venda in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Venda> VendaReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Venda>("eFast.VendaVendaItens", "Venda");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Venda>("eFast.VendaVendaItens", "Venda", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for eFast.Venda in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="eFast", Name="Venda")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Venda : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Venda object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="dhEmit">Initial value of dhEmit.</param>
        /// <param name="cDest">Initial value of cDest.</param>
        /// <param name="tpVenda">Initial value of tpVenda.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Venda CreateVenda(int id, string dhEmit, string cDest, string tpVenda)
        {
            Venda venda = new Venda();
            venda.Id = id;
            venda.dhEmit = dhEmit;
            venda.cDest = cDest;
            venda.tpVenda = tpVenda;
            return venda;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property dhEmit in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string dhEmit
        {
            get
            {
                return this._dhEmit;
            }
            set
            {
                this.OndhEmitChanging(value);
                this.ReportPropertyChanging("dhEmit");
                this._dhEmit = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("dhEmit");
                this.OndhEmitChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _dhEmit;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndhEmitChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndhEmitChanged();
        /// <summary>
        /// Codigo Destinatario
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cDest
        {
            get
            {
                return this._cDest;
            }
            set
            {
                this.OncDestChanging(value);
                this.ReportPropertyChanging("cDest");
                this._cDest = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("cDest");
                this.OncDestChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cDest;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncDestChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncDestChanged();
        /// <summary>
        /// There are no comments for property tpVenda in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string tpVenda
        {
            get
            {
                return this._tpVenda;
            }
            set
            {
                this.OntpVendaChanging(value);
                this.ReportPropertyChanging("tpVenda");
                this._tpVenda = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("tpVenda");
                this.OntpVendaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _tpVenda;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntpVendaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntpVendaChanged();
        /// <summary>
        /// There are no comments for VendaItens in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eFast", "VendaVendaItens", "VendaItens")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<VendaItens> VendaItens
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<VendaItens>("eFast.VendaVendaItens", "VendaItens");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<VendaItens>("eFast.VendaVendaItens", "VendaItens", value);
                }
            }
        }
    }
}
