//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zip.TefDial {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MultiPlus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MultiPlus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zip.TefDial.MultiPlus", typeof(MultiPlus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\TEF_DIAL\REQ\.
        /// </summary>
        internal static string DiretorioReq {
            get {
                return ResourceManager.GetString("DiretorioReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\TEF_DIAL\RESP\.
        /// </summary>
        internal static string DiretorioResp {
            get {
                return ResourceManager.GetString("DiretorioResp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.001.
        /// </summary>
        internal static string NameFileAtivo {
            get {
                return ResourceManager.GetString("NameFileAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntPos.001.
        /// </summary>
        internal static string NameFileReq {
            get {
                return ResourceManager.GetString("NameFileReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntPos.tmp.
        /// </summary>
        internal static string NameFileReqTemp {
            get {
                return ResourceManager.GetString("NameFileReqTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntPos.sts.
        /// </summary>
        internal static string NameFileRespTemp {
            get {
                return ResourceManager.GetString("NameFileRespTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntPos.001.
        /// </summary>
        internal static string NomeFileResp {
            get {
                return ResourceManager.GetString("NomeFileResp", resourceCulture);
            }
        }
    }
}
